spring:
  datasource:
    name: sagw
    url: jdbc:mysql://10.1.9.1:3306/sagw?useUnicode=true&characterEncoding=UTF-8
    username: sagw
    password: Pa$$w0rd2020
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      maximum-pool-size: 50
      connection-test-query: SELECT 1

server:
  connection-timeout: 30s

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8096/material/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: false
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: false   #是否开启文档功能
  group-configs:
    - group: '原材料补差接口'   #分组名称
      paths-to-match: '/**'   #配置需要匹配的路径,默认为/**
      packages-to-scan: com.sagw.meterial    #配置要扫描包的路径,一般配置到启动类所在的包名

# knife4j的增强配置，不需要增强可以不配(建议配置一下) 增强后，文档地址 http://127.0.0.1:8096/material/doc.html
knife4j:
  enable: false    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文

